<a href="https://colab.research.google.com/github/Git34Smakin/codez/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Path to your dataset inside 'dataset' folder in Drive
file_path = "/content/drive/MyDrive/dataset/mydataset.csv"

# Load the dataset
import pandas as pd
# Define column names based on the dataset documentation or content
column_names = [
    "symboling", "normalized-losses", "make", "fuel-type", "aspiration",
    "num-of-doors", "body-style", "drive-wheels", "engine-location",
    "wheel-base", "length", "width", "height", "curb-weight", "engine-type",
    "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke",
    "compression-ratio", "horsepower", "peak-rpm", "city-mpg", "highway-mpg",
    "car-price"
]
df = pd.read_csv(file_path, header=None, names=column_names)


# Show first 5 rows
display(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,car-price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,NaN

Handling missing values

In [5]:
import pandas as pd
import numpy as np

# Assuming your data is in a CSV file named 'data.csv'
try:
    df = pd.read_csv(file_path, header=None, names=column_names)
except FileNotFoundError:
    print("Error: 'data.csv' not found. Please make sure the data file is in the correct location.")
    # You might want to add an exit or raise an exception here if the file is essential
    exit()

df.replace("?", np.nan, inplace=True)
df.dropna(subset=["car-price"], inplace=True)  # drop rows missing price
df["horsepower"] = df["horsepower"].astype(float).fillna(df["horsepower"].mean())

TypeError: can only concatenate str (not "int") to str

Converting data types

Removing duplicates

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
# --- Data Cleaning and Preprocessing ---

import numpy as np
import pandas as pd # Import pandas

# Load data into a DataFrame
# Assuming your data is in a CSV file named 'data.csv'
try:
    df = pd.read_csv('mydataset.csv')
except FileNotFoundError:
    print("Error: 'data.csv' not found. Please make sure the data file is in the correct location.")
    # You might want to add an exit or raise an exception here if the file is essential
    exit()


# 1. Replace "?" with NaN
df.replace("?", np.nan, inplace=True)

# 2. Drop duplicates
df.drop_duplicates(inplace=True)

# 3. Convert numerical columns from object to float
numeric_cols = ["normalized-losses", "bore", "stroke",
                "horsepower", "peak-rpm", "car-price"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# 4. Handle missing values
# Drop rows where car-price is missing (target variable)
df.dropna(subset=["car-price"], inplace=True)

# Impute numerical columns with mean
for col in ["normalized-losses", "bore", "stroke", "horsepower", "peak-rpm"]:
    df[col].fillna(df[col].astype(float).mean(), inplace=True)

# Impute categorical columns with mode
for col in ["num-of-doors"]:
    df[col].fillna(df[col].mode()[0], inplace=True)

# 5. Check cleaned dataset info
print("After preprocessing:")
print(df.info())
print("Number of missing values per column:")
print(df.isnull().sum())

Error: 'data.csv' not found. Please make sure the data file is in the correct location.
After preprocessing:
<class 'pandas.core.frame.DataFrame'>
Index: 197 entries, 0 to 207
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          197 non-null    int64
 1   normalized-losses  197 non-null    float64
 2   make               197 non-null    object
 3   fuel-type          197 non-null    object
 4   aspiration         197 non-null    object
 5   num-of-doors       197 non-null    object
 6   body-style         197 non-null    object
 7   drive-wheels       197 non-null    object
 8   engine-location    197 non-null    object
 9   wheel-base         197 non-null    float64
 10  length             197 non-null    float64
 11  width              197 non-null    float64
 12  height             197 non-null    float64
 13  curb-weight        197 non-null    int64
 14  engine-type        197 non-null    object
 15  num-of-cylinders   197 non-null    object
 16  engine-size        197 non-null    int64
 17  fuel-system        197 non-null    object
 18  bore               197 non-null    float64
 19  stroke             197 non-null    float64
 20  compression-ratio  197 non-null    float64
 21  horsepower         197 non-null    float64
 22  peak-rpm           197 non-null    float64
 23  city-mpg           197 non-null    int64
 24  highway-mpg        197 non-null    int64
 25  car-price          197 non-null    int64
dtypes: float64(10), int64(6), object(10)
memory usage: 41.6+ KB
None
Number of missing values per column:
symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
car-price            0
dtype: int64

/tmp/ipython-input-3354503112.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].astype(float).mean(), inplace=True)
/tmp/ipython-input-3354503112.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].astype(float).mean(), inplace=True)
/tmp/ipython-input-3354503112.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].astype(float).mean(), inplace=True)
/tmp/ipython-input-3354503112.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].astype(float).mean(), inplace=True)
/tmp/ipython-input-3354503112.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].astype(float).mean(), inplace=True)
/tmp/ipython-input-3354503112.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)